version: '3'
services:
  php-apache:
    build: ./
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/laravel
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql

  mysql:
    build: ./db
    ports:
      - 4306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
