version: '3'
services:
  php-apache:
    container_name: laravel-container
    build: ./
    ports:
      - 8000:80
      - 9003:9003
    volumes:
      - ./src/:/var/www/laravel
    depends_on:
      - mysql

  mysql:
    container_name: mysql-container
    build: ./db
    ports:
      - 4306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql

  mysql-test:
    container_name: mysql-test-container
    build: ./db
    ports:
      - 5306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/testdata:/var/lib/mysql
